### ISSUE TITLE
Readme.md - moduleoffset and dir not defined

### ISSUE THREAD

**Issue by ghost** [joele89/Edmosoft.IO#1]
`compressedModule.Position = moduleOffset; //moduleOffset is read from structures in the "dir" stream from the CompoundFile, "dir" is also compressed with vbaCompression`
Either I am getting something wrong, but moduleOffset and dir are not defined in the readme example

**Comment by joele89** [comment]
Yes that is correct,
dir is found in other parts of the compound file (mdcf), but also has it's own byte packing even after being decompressed by the vbaStreamReader.
moduleOffset is one of the values found in dir, 

A separate library is currently undergoing a major refactoring that will have a decoder for the 'dir' object.
Once I publish the other library, you would likely access attributes similar to the following (assuming you use my library)
vbaProject.Modules[moduleName].ModuleOffset;

**Comment by joele89** [comment]
https://www.nuget.org/packages/Edmosoft.Office.vbaProject/0.0.1
